import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import "bootstrap/dist/css/bootstrap.min.css";
import axios from "axios";

export default function Home() {
  const [hasToken, sethasToken] = useState(false);
  const [token, setToken] = useState(null);
  const [userInfo, setuserInfo] = useState(null);
  const [PlasyList, setPlasyList] = useState(null);

  const router = useRouter();
  useEffect(() => {
    if (router.query.token) {
      console.log("Have Token");
      setToken(router.query.token);
      getUserInfo(router.query.token);
      getUserPlayList(router.query.token);
      sethasToken(true);
    } else {
      sethasToken(false);
      console.log("No Token");
    }
  }, [router]);

  const getUserInfo = async (token2) => {
    let config = {
      method: "get",
      url: "https://api.spotify.com/v1/me",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: "Bearer " + token2,
      },
    };
    let res = await axios(config);
    setuserInfo(res.data);
  };

  const getUserPlayList = async (token2) => {
    let config = {
      method: "get",
      url: "https://api.spotify.com/v1/me/playlists",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: "Bearer " + token2,
      },
    };
    let res = await axios(config);
    console.log("🚀 ~ file: index.js ~ line 41 ~ getUserInfo ~ res", res.data);
    setPlasyList(res.data);
  };

  return (
    <div>
      <Head>
        <title>Tepify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-3">
        <div className="card">
          {hasToken && userInfo != null ? (
            <div className="card-body ">
              <div className="d-flex justify-content-center flex-column">
                <div>
                  <b>display_name</b> : {userInfo.display_name}
                </div>
                <div>
                  <b>id</b> : {userInfo.id}
                </div>
                <div>
                  <b>country</b> : {userInfo.country}
                </div>
              </div>
              <hr />
              {PlasyList !== null ? (
                <div className="list-group ">
                  {PlasyList.items.map((item) => (
                    <div class="list-group-item d-flex flex-row">
                      
                      <div class="position-relative">
                        <span class="position-absolute top-0 start-0 translate-middle badge rounded-pill bg-success">
                          {item.tracks.total}
                        </span>
                        <img
                          width="100"
                          src={
                            item.images.length != 0
                              ? item.images[0].url
                              : "/cover_null.png"
                          }
                        />
                      </div>
                      <div className="d-flex flex-column ms-3 overflow-auto">
                        <h5>{item.name}</h5>
                        <div
                          style={{ heigt: "4rem !important" }}
                          className="overflow-auto"
                        >
                          {item.description}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                ""
              )}
            </div>
          ) : (
            <div className="card-body d-flex justify-content-center">
              <a href="/api/login" className="btn btn-primary">
                Login With Spotify
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
